map_type: costmap

obstacle_range: 1.0 # 2.0 #before 1.0
raytrace_range: 2.0 # 3.0 #before 2.0

transform_tolerance: 0.2 # 0.2

# robot_radius: 0.35 # 0.0
footprint: [[-0.2, -0.17], [-0.2, 0.175], [0.2, 0.175], [0.2, -0.175]]
inflation_radius: 0.2 # 0.0 before 0.4
cost_scaling_factor: 5.0 #before 5.0

observation_sources: laser_scan_slaser_frame

# laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
