global_costmap:
   global_frame: odom #map
   robot_base_frame: base_footprint
   update_frequency: 2.0
   publish_frequency: 2.0
   width: 15.0
   height: 15.0
   resolution: 0.01
   static_map: false #true
   rolling_window: true
